### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by Lcchy** [GModal/pd2jack#7]
Hi, I stumbled upon this project by chance and found it well documented but also close to the way I am using Pd at the moment.
Could you please explain how this deviates from using Pd with the  `-nogui -jack` options? 
Thanks a lot for your help.

**Comment by GModal** [comment]
Yeah, Hi, good question. Maybe not enough to make it worth using for some :-)

1) It's a single executable, not an extensive installation. There are libraries, of course, but most AV systems would have them.

2) Facilitates inter-process communication. The (extra) OSC hooks make sending and receiving, both to the patch and the process, easier. Loading (and unloading) patches via OSC is simple, as is bypassing and turning DSP on/off.

2b) Working off `#2`: It's much easier to use existing patches with OSC control.

This is the real reason for the project -- to easily control Pd via external GUI programs. Both on a host computer, and via networking...for a stompbox, for instance.

An external GUI also can off-load some of the computational stuff to the controller. Not for audio processing, but sequencing, scale/chord computation, interface, etc.

3) Ability to send MIDI data directly to pd2jack via OSC (through notein, ctlin, etc), not just the MIDI ports.

4) Multiple instances easier with the "descriptor" option: each running instance has an internal ID. Multiple instances, perhaps on different micros, but controlled by one mobile device.


I've unfortunately not had a chance to compile and test this on a micro (like Raspberry Pi), which was one of the motivations for it. I'd like to start with a RPi Zero W 2 (and a simple USB audio interface), but they have been difficult to come by.

**Comment by Lcchy** [comment]
Thank you for the information! The extended OSC interfacing sounds really neat, I'll surely give it a try when I have time to port my setup!
